create table
  public.barrel_orders (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    size text null,
    price integer null,
    color text null,
    constraint barrel_orders_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.cart_items (
    id bigint generated by default as identity,
    r integer not null default 0,
    g integer null default 0,
    b integer null default 0,
    t integer null default 0,
    cart_id bigint not null,
    sku text null,
    quantity integer null,
    price integer null,
    constraint cart_items_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.carts (
    id bigint generated by default as identity,
    customer_id integer null,
    price integer null default 0,
    constraint carts_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.catalog (
    id bigint generated by default as identity,
    r smallint not null,
    g smallint null,
    b smallint null,
    t smallint null,
    price integer null,
    quantity integer null,
    name text null,
    constraint catalog_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.customers (
    id bigint generated by default as identity,
    name text not null,
    constraint constumers_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.global_inventory (
    id bigint generated by default as identity,
    gold integer not null,
    constraint global_inventory_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.invoices (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    customer_id integer null,
    customer_name text null,
    item_name text null,
    price integer null,
    quantity integer null,
    constraint invoices_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.ml (
    id bigint generated by default as identity,
    redml integer not null,
    greenml integer null,
    blueml integer null,
    darkml integer null,
    constraint ml_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.potion_orders (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text null,
    quantity integer null,
    constraint potion_orders_pkey primary key (id)
  ) tablespace pg_default;